#DeepCode Configuration
#Mon May 11 12:35:59 ICT 2026
crawl.interval.hours=24
crawl.max.submissions=50
db.path=deepcode.db
gemini.api.key=AIzaSyDOrIUtmo-F0BB-9U76kEMV4WDzdmLQPZQ
gemini.api.url=https\://generativelanguage.googleapis.com/v1beta/models/
gemini.model=gemini-2.0-flash
